name: xylophone
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  cupertino_icons: ^1.0.4
  audioplayers: ^0.17.4
  # Use Audioplayers dependency version 0.17.4 (currently 0.20.1 in 12/08/21)

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

